import type {Dispatch,FormEvent,SetStateAction} from 'react'
import {Archive,Mail,RotateCcw,Send,UsersRound} from 'lucide-react'
import type {Project,Task} from '../../domain/types'

export function ProjectLifecyclePanel({projects,setProjects,tasks,setTasks}:{projects:Project[];setProjects:Dispatch<SetStateAction<Project[]>>;tasks:Task[];setTasks:Dispatch<SetStateAction<Task[]>>}){
  const archived=projects.filter(project=>project.archivedAt)
  const active=projects.filter(project=>!project.archivedAt)
  const archiveProject=(project:Project)=>{const unfinished=tasks.filter(task=>task.project===project.title&&!task.done);if(!window.confirm(`將「${project.title}」標記完成並封存？${unfinished.length?`目前還有 ${unfinished.length} 個未完成任務。`:''}`))return;if(unfinished.length){const choice=window.prompt('未完成任務如何處理？輸入 1 標記完成、2 移回收集匣、3 保留在封存專案','3');if(choice==='1')setTasks(current=>current.map(task=>task.project===project.title?{...task,done:true,status:'完成',progress:100}:task));if(choice==='2')setTasks(current=>current.map(task=>task.project===project.title&&!task.done?{...task,project:'收集匣',inbox:true}:task))}const retrospective=window.prompt('留下專案復盤摘要（可略過）','')?.trim();const now=new Date().toISOString();setProjects(current=>current.map(item=>item.id===project.id?{...item,status:'完成',progress:100,completedAt:now,archivedAt:now,retrospective:retrospective||item.retrospective}:item))}
  const restoreProject=(id:number)=>setProjects(current=>current.map(item=>item.id===id?{...item,status:'進行中',archivedAt:undefined}:item))
  const invite=(event:FormEvent<HTMLFormElement>,project:Project)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const email=String(data.get('email')||'').trim().toLowerCase();const role=String(data.get('role')) as '編輯者'|'檢視者';if(!/^\S+@\S+\.\S+$/.test(email))return;setProjects(current=>current.map(item=>item.id===project.id?{...item,collaborators:[...(item.collaborators||[]).filter(person=>person.email!==email),{email,role,status:'待接受',invitedAt:new Date().toISOString()}]}:item));form.reset()}
  return <section className="project-lifecycle"><article className="card collaborator-panel"><div className="card-head"><div><span className="kicker">COLLABORATION</span><h2>夥伴與共編邀請</h2></div><UsersRound/></div><p>輸入 email 建立邀請。純本機版本會記錄邀請並開啟郵件草稿；跨裝置共編將在雲端同步接入後生效。</p>{active.map(project=><div className="project-collab-row" key={project.id}><div><b>{project.title}</b>{project.collaborators?.map(person=><span key={person.email}>{person.email}・{person.role}・{person.status}</span>)}</div><form onSubmit={event=>invite(event,project)}><Mail/><input name="email" type="email" required placeholder="partner@example.com"/><select name="role"><option>編輯者</option><option>檢視者</option></select><button type="submit" title="建立邀請"><Send/></button></form>{project.collaborators?.filter(person=>person.status==='待接受').slice(-1).map(person=><a key={person.email} href={`mailto:${encodeURIComponent(person.email)}?subject=${encodeURIComponent(`邀請共編：${project.title}`)}&body=${encodeURIComponent(`我邀請你一起參與「${project.title}」。目前邀請已記錄於 Personal Growth OS；雲端共編啟用後即可接受加入。`)}`}>開啟郵件草稿</a>)}</div>)}</article><article className="card archive-panel"><div className="card-head"><div><span className="kicker">PROJECT LIFECYCLE</span><h2>完成與封存</h2></div><Archive/></div><p>封存不會刪除任務與紀錄，後續需要時可重新啟用。</p>{active.map(project=><div className="archive-row" key={project.id}><div><b>{project.title}</b><span>{project.progress}%・{project.deadline}</span></div><button onClick={()=>archiveProject(project)}><Archive/>完成並封存</button></div>)}{archived.map(project=><div className="archive-row archived" key={project.id}><div><b>{project.title}</b><span>封存於 {project.archivedAt?.slice(0,10)}</span></div><button onClick={()=>restoreProject(project.id)}><RotateCcw/>重新啟用</button></div>)}</article></section>
}
