import type {FormField} from '../components/RecordModal'
import type {FormKind} from '../domain/types'
export type FormConfig={title:string;subtitle:string;fields:FormField[]}
const opts=(values:string[])=>values.map(value=>({label:value,value}))
export const formConfigs:Record<Exclude<FormKind,null>,FormConfig>={
  goal:{title:'建立 SMART Goal',subtitle:'先定義想達到什麼，以及如何衡量。',fields:[{name:'title',label:'目標名稱',required:true},{name:'area',label:'人生領域',type:'select',defaultValue:'成長',options:opts(['學習','職涯','財務','健康','生活','成長'])},{name:'current',label:'目前數值',type:'number',defaultValue:0},{name:'target',label:'目標數值',type:'number',required:true,defaultValue:100},{name:'unit',label:'單位',defaultValue:'%'},{name:'deadline',label:'期限',type:'date',required:true},{name:'reason',label:'為什麼重要',type:'textarea',required:true}]},
  project:{title:'建立專案',subtitle:'定義成果、角色、負責人、期限、容量與目前風險。',fields:[{name:'title',label:'專案名稱',required:true},{name:'area',label:'領域',defaultValue:'成長'},{name:'role',label:'人生角色',defaultValue:'個人成長'},{name:'description',label:'專案說明',type:'textarea'},{name:'goal',label:'預期成果',required:true,type:'textarea'},{name:'owner',label:'負責人',defaultValue:'自己'},{name:'startDate',label:'開始日期',type:'date'},{name:'deadline',label:'截止日期',type:'date',required:true},{name:'weeklyCapacity',label:'每週可投入時數',type:'number',defaultValue:10},{name:'status',label:'狀態',type:'select',defaultValue:'規劃中',options:opts(['規劃中','進行中','暫停'])},{name:'risk',label:'目前主要風險',type:'textarea'}]},
  work:{title:'新增工作身份',subtitle:'記錄組織、角色與計價方式。',fields:[{name:'name',label:'工作名稱',required:true},{name:'organization',label:'組織／客戶',required:true},{name:'role',label:'角色',required:true},{name:'type',label:'工作類型',type:'select',defaultValue:'自由接案',options:opts(['全職','兼職','家教','自由接案','研究助理'])},{name:'rate',label:'費率',type:'number',defaultValue:0},{name:'unit',label:'計價單位',defaultValue:'時'}]},
  exam:{title:'新增考試',subtitle:'設定目前程度、目標與考試日期。',fields:[{name:'name',label:'考試名稱',required:true},{name:'type',label:'考試類型',required:true},{name:'date',label:'考試日期',type:'date',required:true},{name:'current',label:'目前分數',type:'number',defaultValue:0},{name:'target',label:'目標分數',type:'number',required:true,defaultValue:100}]},
  transaction:{title:'新增財務交易',subtitle:'記錄收入或支出，帳戶餘額會同步更新。',fields:[{name:'type',label:'類型',type:'select',defaultValue:'支出',options:opts(['支出','收入'])},{name:'amount',label:'金額',type:'number',required:true,min:0},{name:'category',label:'分類',required:true},{name:'note',label:'說明',required:true},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},
  account:{title:'新增帳戶',subtitle:'建立現金、銀行或投資帳戶。',fields:[{name:'name',label:'帳戶名稱',required:true},{name:'type',label:'帳戶類型',type:'select',defaultValue:'銀行帳戶',options:opts(['銀行帳戶','現金','電子支付','投資帳戶'])},{name:'balance',label:'期初餘額',type:'number',defaultValue:0}]},
  holding:{title:'新增投資交易',subtitle:'建立新資產，或記錄第一筆買入。',fields:[{name:'symbol',label:'代號',required:true},{name:'name',label:'資產名稱',required:true},{name:'type',label:'資產類型',type:'select',defaultValue:'ETF',options:opts(['ETF','股票','債券','Crypto','基金'])},{name:'quantity',label:'數量',type:'number',required:true,min:0},{name:'price',label:'成交價格',type:'number',required:true,min:0},{name:'date',label:'交易日期',type:'date',required:true,defaultValue:'2026-08-13'}]},
  note:{title:'新增筆記',subtitle:'讓想法可以被搜尋、連結與再次使用。',fields:[{name:'title',label:'標題',required:true},{name:'tag',label:'標籤',defaultValue:'Idea'},{name:'content',label:'內容',type:'textarea',required:true}]},journal:{title:'新增日記',subtitle:'留下一段真實且有用的反思。',fields:[{name:'title',label:'標題',required:true},{name:'type',label:'類型',type:'select',defaultValue:'Daily',options:opts(['Daily','Learning','Career','Project','Reflection'])},{name:'mood',label:'心情 1–5',type:'number',min:1,max:5,defaultValue:4},{name:'content',label:'內容',type:'textarea',required:true}]},habit:{title:'新增習慣',subtitle:'從一個小到能每天完成的行動開始。',fields:[{name:'name',label:'習慣名稱',required:true},{name:'category',label:'分類',defaultValue:'成長'}]},
  waiting:{title:'新增等待項目',subtitle:'記錄正在等待誰、什麼，以及何時跟進。',fields:[{name:'title',label:'等待事項',required:true},{name:'followUp',label:'跟進日期',type:'date',required:true},{name:'note',label:'備註',type:'textarea'}]},someday:{title:'新增未來想法',subtitle:'先保存可能性，不需要現在承諾。',fields:[{name:'title',label:'想法',required:true},{name:'note',label:'什麼情況下會開始？',type:'textarea'}]},study:{title:'新增學習紀錄',subtitle:'記錄投入時間、題數與正確率。',fields:[{name:'subject',label:'科目',required:true},{name:'minutes',label:'學習分鐘',type:'number',required:true,min:1},{name:'questions',label:'完成題數',type:'number',defaultValue:0},{name:'correct',label:'答對題數',type:'number',defaultValue:0},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},mistake:{title:'新增錯題',subtitle:'留下錯誤原因與正確概念，讓失誤可以被修正。',fields:[{name:'subject',label:'科目',required:true},{name:'source',label:'題目來源',required:true},{name:'reason',label:'錯誤原因',type:'textarea',required:true},{name:'concept',label:'正確概念',type:'textarea',required:true}]},
  exercise:{title:'新增運動紀錄',subtitle:'記錄運動類型、時間與強度。',fields:[{name:'type',label:'運動類型',required:true},{name:'duration',label:'分鐘',type:'number',required:true,min:1},{name:'intensity',label:'強度',type:'select',defaultValue:'中',options:opts(['低','中','高'])},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},sleep:{title:'新增睡眠紀錄',subtitle:'記錄睡眠時數與主觀品質。',fields:[{name:'hours',label:'睡眠時數',type:'number',required:true,min:0,max:24},{name:'quality',label:'品質 1–5',type:'number',required:true,min:1,max:5,defaultValue:4},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},body:{title:'新增身體數據',subtitle:'用趨勢觀察，不需要被單次數字綁架。',fields:[{name:'weight',label:'體重 kg',type:'number',required:true,min:0},{name:'bodyFat',label:'體脂 %',type:'number',min:0},{name:'waist',label:'腰圍 cm',type:'number',min:0},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},
  symptom:{title:'新增症狀紀錄',subtitle:'記錄身體訊號與當下情境。',fields:[{name:'name',label:'症狀',required:true},{name:'note',label:'描述',type:'textarea'},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},recovery:{title:'新增恢復活動',subtitle:'記錄真正幫助你恢復能量的活動。',fields:[{name:'name',label:'活動',required:true},{name:'minutes',label:'分鐘',type:'number',min:0},{name:'note',label:'感受',type:'textarea'},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'}]},event:{title:'新增行事曆事件',subtitle:'建立有明確時間的承諾，也可以設定重複規則。',fields:[{name:'title',label:'事件名稱',required:true},{name:'date',label:'日期',type:'date',required:true,defaultValue:'2026-08-13'},{name:'start',label:'開始時間',required:true,defaultValue:'09:00'},{name:'end',label:'結束時間',required:true,defaultValue:'10:00'},{name:'category',label:'分類',type:'select',defaultValue:'個人',options:opts(['工作','課程','考試','專案','健康','恢復','社交','個人'])},{name:'recurrence',label:'重複',type:'select',defaultValue:'無',options:opts(['無','每天','每週','每月'])},{name:'note',label:'地點／備註',type:'textarea'}]},
}
