import {FormEvent,ReactNode,useEffect,useState} from 'react'
import {ArrowRight,Eye,EyeOff,Flame,LockKeyhole,Mail,UserRound} from 'lucide-react'
import {getSession,loginUser,logoutUser,onAuthStateChange,registerUser,type AuthSession} from './authStorage'

export function AuthGate({children}:{children:(session:AuthSession,logout:()=>void)=>ReactNode}){
  const [session,setSession]=useState<AuthSession|null>(null)
  const [loading,setLoading]=useState(true)
  const [mode,setMode]=useState<'login'|'register'>('login')
  const [showPassword,setShowPassword]=useState(false)
  const [submitting,setSubmitting]=useState(false)
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  useEffect(()=>{let active=true;getSession().then(value=>{if(active)setSession(value)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'無法讀取登入狀態')}).finally(()=>{if(active)setLoading(false)});const unsubscribe=onAuthStateChange(value=>{if(active){setSession(value);setLoading(false)}});return()=>{active=false;unsubscribe()}},[])
  if(loading)return <main className="auth-page"><section className="auth-panel"><p>正在連接 Supabase…</p></section></main>
  if(session)return children(session,()=>{void logoutUser().catch(reason=>setError(reason instanceof Error?reason.message:'登出失敗'))})
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');setNotice('');const data=new FormData(event.currentTarget);const name=String(data.get('name')||'').trim();const email=String(data.get('email')||'').trim();const password=String(data.get('password')||'');if(mode==='register'&&name.length<2)return setError('顯示名稱至少需要 2 個字元');if(!/^\S+@\S+\.\S+$/.test(email))return setError('請輸入有效的電子郵件');if(password.length<8)return setError('密碼至少需要 8 個字元');setSubmitting(true);try{if(mode==='register'){const result=await registerUser(name,email,password);if(result.session)setSession(result.session);else{setNotice('註冊成功！請到信箱點擊驗證連結，再回來登入。');setMode('login')}}else{const result=await loginUser(email,password);if(result)setSession(result)}}catch(reason){setError(reason instanceof Error?reason.message:'操作失敗，請稍後再試')}finally{setSubmitting(false)}}
  return <main className="auth-page"><section className="auth-intro"><div className="auth-brand"><span><Flame/></span>Growth <b>OS</b></div><div><span className="auth-kicker">PERSONAL GROWTH SYSTEM</span><h1>把每一天，連成你想成為的樣子。</h1><p>在同一個地方管理任務、目標、健康、學習與財務，讓成長變得清楚而可持續。</p></div><small>帳號由 Supabase 安全管理</small></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><span className="auth-icon"><LockKeyhole/></span><h2>{mode==='login'?'歡迎回來':'建立你的帳號'}</h2><p>{mode==='login'?'登入並繼續今天的成長計畫。':'開始建立屬於你的個人成長系統。'}</p>{mode==='register'&&<label><span>顯示名稱</span><div><UserRound/><input name="name" autoComplete="name" placeholder="你的名字"/></div></label>}<label><span>電子郵件</span><div><Mail/><input name="email" type="email" autoComplete="email" placeholder="name@example.com"/></div></label><label><span>密碼</span><div><LockKeyhole/><input name="password" type={showPassword?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="至少 8 個字元"/><button type="button" aria-label={showPassword?'隱藏密碼':'顯示密碼'} onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error" role="alert">{error}</div>}{notice&&<div className="auth-error" role="status">{notice}</div>}<button className="auth-submit" disabled={submitting}>{submitting?'處理中…':mode==='login'?'登入':'建立帳號'}<ArrowRight/></button><div className="auth-switch">{mode==='login'?'還沒有帳號？':'已經有帳號？'}<button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setNotice('')}}>{mode==='login'?'立即註冊':'返回登入'}</button></div></form></section></main>
}
