import type { Energy, Quadrant } from "../../domain/types";
export type CaptureKind="任務"|"行程"|"專案"|"筆記"|"提醒"|"資源"|"電影"|"書籍"|"財務"|"以後再做";
export type CaptureSuggestion={raw:string;title:string;kind:CaptureKind;category:string;quadrant:Quadrant;estimate:number;energy:Energy;due?:string};
const dateKey=(date:Date)=>date.toLocaleDateString("en-CA");
function inferDue(input:string,now:Date){if(/今天|今晚/.test(input))return dateKey(now);if(/明天|明早|明晚/.test(input)){const date=new Date(now);date.setDate(date.getDate()+1);return dateKey(date)}const days:Array<[RegExp,number]>=[[/星期[日天]|週[日天]/,0],[/星期一|週一/,1],[/星期二|週二/,2],[/星期三|週三/,3],[/星期四|週四/,4],[/星期五|週五/,5],[/星期六|週六/,6]];const match=days.find(([pattern])=>pattern.test(input));if(!match)return;const date=new Date(now);date.setDate(date.getDate()+(match[1]-date.getDay()+7)%7);return dateKey(date)}
function inferMinutes(input:string){const hours=input.match(/(?:大概|約|預計)?\s*(\d+(?:\.\d+)?)\s*(?:個)?小時/);if(hours)return Math.max(5,Math.round(Number(hours[1])*60));const minutes=input.match(/(?:大概|約|預計)?\s*(\d+)\s*分鐘/);return minutes?Math.max(5,Number(minutes[1])):30}
function inferKind(input:string):CaptureKind{if(/想看|電影|影集|片單/.test(input))return"電影";if(/想讀|想買.*書|書單|這本書/.test(input))return"書籍";if(/繳.*費|帳單|支出|收入|訂閱|存錢/.test(input))return"財務";if(/靈感|筆記|記下|心得/.test(input))return"筆記";if(/有空|哪天|以後|someday/i.test(input))return"以後再做";if(/提醒我|記得/.test(input))return"提醒";if(/開會|看診|聚餐|課程|活動/.test(input)&&/\d{1,2}[:：點]/.test(input))return"行程";return"任務"}
function cleanTitle(input:string){return input.replace(/(?:大概|約|預計)?\s*\d+(?:\.\d+)?\s*(?:個)?小時/g,"").replace(/(?:大概|約|預計)?\s*\d+\s*分鐘/g,"").replace(/(?:星期|週)[一二三四五六日天][前之]?/g,"").replace(/(?:今天|今晚|明天|明早|明晚)前?/g,"").replace(/[，,。]\s*$/g,"").replace(/\s{2,}/g," ").trim()}
export function analyzeCapture(input:string,now=new Date()):CaptureSuggestion{const raw=input.trim(),kind=inferKind(raw),due=inferDue(raw,now);const energy:Energy=/研究|寫|修改|設計|規劃|決定|程式/.test(raw)?"高":/回覆|整理|繳.*費|預約|查詢/.test(raw)?"低":"中";const category=kind==="財務"?"財務":kind==="電影"||kind==="書籍"?"興趣":"一般";return{raw,title:cleanTitle(raw)||raw,kind,category,quadrant:due?"Q1":"Q2",estimate:inferMinutes(raw),energy,due}}
