import {FormEvent} from 'react'
import {X} from 'lucide-react'
import type {Energy,Project,Task,TaskPriority,TaskStatus} from '../../domain/types'
import {useDialog} from '../../hooks/useDialog'

export function TaskEditorModal({task,tasks,projects,categories,roles,onSave,onClose}:{task:Task;tasks:Task[];projects:Project[];categories:string[];roles:string[];onSave:(task:Task)=>void;onClose:()=>void}){
  useDialog(onClose)
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const status=String(data.get('status')) as TaskStatus;const priority=String(data.get('priority')) as TaskPriority;const quadrant=({緊急:'Q1',高:'Q2',中:'Q3',低:'Q4'} as const)[priority];const projectName=String(data.get('project'));onSave({...task,title:String(data.get('title')).trim(),category:String(data.get('category')),role:task.role||projects.find(project=>project.title===projectName)?.role||roles[0]||'個人成長',project:projectName,assignee:String(data.get('assignee')).trim()||'自己',priority,quadrant,due:String(data.get('due')),scheduledStart:String(data.get('scheduledStart')),scheduledEnd:String(data.get('scheduledEnd')),status,done:status==='完成',progress:status==='完成'?100:Number(data.get('progress'))||0,estimate:Number(data.get('estimate'))||30,energy:String(data.get('energy')) as Energy,nextAction:String(data.get('nextAction')).trim(),risk:String(data.get('risk')).trim(),dependencyId:Number(data.get('dependencyId'))||undefined,reminder:data.get('reminder')==='on'})}
  return <div className="modal-back" onMouseDown={onClose}><form className="modal task-editor" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><span className="kicker">TASK EDITOR</span><h2>編輯任務</h2></div><button type="button" onClick={onClose} aria-label="關閉"><X/></button></div><div className="task-editor-fields">
    <label className="full-field">任務名稱<input name="title" required defaultValue={task.title}/></label>
    <label>類別<select name="category" defaultValue={task.category||'一般'}>{categories.map(value=><option key={value}>{value}</option>)}</select></label>
    <label>所屬專案<select name="project" defaultValue={task.project}><option>收集匣</option>{projects.filter(project=>!project.archivedAt).map(project=><option key={project.id}>{project.title}</option>)}</select></label>
    <label>負責人<input name="assignee" defaultValue={task.assignee||'自己'}/></label><label>優先級<select name="priority" defaultValue={task.priority||({Q1:'緊急',Q2:'高',Q3:'中',Q4:'低'} as const)[task.quadrant]}>{(['緊急','高','中','低'] as TaskPriority[]).map(value=><option key={value}>{value}</option>)}</select></label>
    <label>日期<input name="due" type="date" defaultValue={task.due?.match(/^\d{4}-\d{2}-\d{2}$/)?task.due:''}/></label><label>開始時間<input name="scheduledStart" type="time" defaultValue={task.scheduledStart||'09:00'}/></label><label>結束時間<input name="scheduledEnd" type="time" defaultValue={task.scheduledEnd||'10:00'}/></label>
    <label>狀態<select name="status" defaultValue={task.done?'完成':task.status||'待辦'}>{(['待辦','進行中','審核','完成'] as TaskStatus[]).map(value=><option key={value}>{value}</option>)}</select></label><label>完成進度<input name="progress" type="number" min="0" max="100" step="5" defaultValue={task.progress??(task.done?100:0)}/></label><label>預估分鐘<input name="estimate" type="number" min="5" defaultValue={task.estimate}/></label><label>精力需求<select name="energy" defaultValue={task.energy}>{(['高','中','低'] as Energy[]).map(value=><option key={value}>{value}</option>)}</select></label>
    <label className="full-field">下一步行動<input name="nextAction" defaultValue={task.nextAction||''}/></label><label className="full-field">風險／阻礙<textarea name="risk" defaultValue={task.risk||''}/></label><label>前置任務<select name="dependencyId" defaultValue={task.dependencyId||''}><option value="">無</option>{tasks.filter(item=>item.id!==task.id&&!item.done).map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="task-reminder"><input name="reminder" type="checkbox" defaultChecked={task.reminder}/><span>開啟到期提醒</span></label>
  </div><div className="modal-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" type="submit">儲存變更</button></div></form></div>
}
